### ISSUE TITLE
Update Node 10.17

### ISSUE THREAD

**Issue by beau-charman** [aesop/aesop-gel#288]
To at least 10.17 - https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#2019-10-22-version-10170-dubnium-lts-bethgriggs

- To address https://github.com/jsdom/jsdom/issues/2939

Should update alongside https://github.com/aesop/aesop-web-ui

**Comment by MkMan** [comment]
This one should be safe to do on Web UI. When I was updating webpack I bumped Node up to either 14 or 12 and it still worked.
