### ISSUE TITLE
BodyCopy component creates 2 elements with the same `id`

### ISSUE THREAD

**Issue by MkMan** [aesop/aesop-gel#420]
https://github.com/aesop/aesop-gel/blob/develop/src/components/BodyCopy/BodyCopy.tsx#L30
https://github.com/aesop/aesop-gel/blob/develop/src/components/BodyCopy/BodyCopy.tsx#L40

**Comment by beau-charman** [comment]
addresses in https://github.com/aesop/aesop-gel/pull/486

**Comment by MkMan** [comment]
> addresses in #486

Can this issue be closed now that the PR is merged?
